version: 2

sources:
  - name: mongo_raw
    schema: spectreco_data
    tables:
      - name: cdata
      - name: cdata_bi_annual
      - name: cdata_bi_annual_forecast
      - name: cdata_month
      - name: cdata_month_forecast
      - name: cdata_quarter
      - name: cdata_quarter_forecast
      - name: cdata_yearly
      - name: cdata_yearly_baseline
      - name: cdata_yearly_forecast
      - name: cdata_yearly_target
      # - name: companies
      # - name: company_sites
      # - name: company_codes
      # - name: standards
      # - name: standard_codes
      # - name: company_frameworks
      # - name: categories