version: 2

sources:
  - name: mongo_raw
    schema: spectreco_dev
    tables:
      - name: cdata
      - name: cdata_bi_annual
      - name: cdata_bi_annual_forecast
      - name: cdata_month
      - name: cdata_month_forecast
      - name: cdata_quarter
      - name: cdata_quarter_forecast
      - name: cdata_yearly
      - name: cdata_yearly_baseline
      - name: cdata_yearly_forecast
      - name: cdata_yearly_target
      - name: companies
      - name: company_sites
      - name: company_codes
      - name: standards
      - name: standard_codes
      - name: company_frameworks
      - name: categories

  # - name: mongo_stg
  #   schema: dw_stg
  #   tables:
  #     - name: cdata_bi_annual_stg
  #     - name: cdata_bi_annual_baseline_stg
  #     - name: cdata_bi_annual_forecast_stg
  #     - name: cdata_bi_annual_target_stg
  #     - name: cdata_month_stg
  #     - name: cdata_month_baseline_stg
  #     - name: cdata_month_forecast_stg
  #     - name: cdata_quarter_stg
  #     - name: cdata_quarter_baseline_stg
  #     - name: cdata_quarter_forecast_stg
  #     - name: cdata_quarter_target_stg
  #     - name: cdata_yearly_stg
  #     - name: cdata_yearly_baseline_stg
  #     - name: cdata_yearly_forecast_stg
  #     - name: cdata_yearly_target_stg
  #     - name: companies_stg
  #     - name: company_sites_stg
  #     - name: company_codes_stg
  #     - name: standards_stg
  #     - name: standard_codes_stg
  #     - name: company_frameworks_stg
  #     - name: categories_stg